/**
 * Carga todos los modelos Mongoose (para utilidades como purge/backup que resuelven nombres de colección).
 */
require('./User');
require('./ViaTramo');
require('./ExistSenVert');
require('./ExistSenHor');
require('./Semaforo');
require('./ControlSemaforo');
require('./CajaInspeccion');
require('./CategorizacionVial');
require('./ObservacionSV');
require('./ObservacionSH');
require('./ObsSemaforo');
require('./ObservacionVia');
require('./PreguntaEncVia');
require('./RespuestaEncVia');
require('./SenVert');
require('./EsquemaPerfil');
require('./UbicSenHor');
require('./Demarcacion');
require('./Zat');
require('./Comuna');
require('./Barrio');
require('./Jornada');
require('./Divipol');
require('./Audit');
require('./BackupEvent');
// Modelos SINC
require('./SincEje');
require('./SincPropiedades');
require('./SincFotoEje');
require('./SincPuente');
require('./SincPonton');
require('./SincObraDrenaje');
require('./SincInterseccion');
require('./SincDefensa');
require('./SincMuro');
require('./SincTalude');
require('./SincTunel');
require('./SincEstructuraPavimento');
require('./SincPrs');
require('./SincSenal');
require('./SincSitioCritico');
require('./SincMc'); // registra SincMcBerma, SincMcCalzada, … (17 capas)
